export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const GETALLCOMPLAINT_REQUEST = "GETALLCOMPLAINT_REQUEST";
export const GETALLCOMPLAINT_SUCCESS = "GETALLCOMPLAINT_SUCCESS";
export const GETALLCOMPLAINT_FAIL = "GETALLCOMPLAINT_FAIL";

export const DELETE_USER = "DELETE_USER";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const SINGLE_USER = "SINGLE_USER";

export const SEARCH_USER = "SEARCH_USER";
