export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const GETALLCOMPLAINT_REQUEST = "GETALLCOMPLAINT_REQUEST";
export const GETALLCOMPLAINT_SUCCESS = "GETALLCOMPLAINT_SUCCESS";
export const GETALLCOMPLAINT_FAIL = "GETALLCOMPLAINT_FAIL";
